### ISSUE TITLE
BlueSky error raised by IC endpoint (reset simulation) with empty body

### ISSUE THREAD

**Issue by thobson88** [alan-turing-institute/bluebird#40]
Although the scenario is successfully reset when the `IC` API endpoint is called with an empty body, the BlueSky console logs the error `Openfile error: Cannot file scenario/IC.scn`.

**Comment by rkm** [comment]
Will look into this. The command we pass through to BlueSky is `IC IC` which should reload the last scenario rather than clearing the simulation completely. We should perhaps implement a separate `reset` endpoint which does what you are expecting, then make the filename argument to the `IC` endpoint required.

**Comment by thobson88** [comment]
Yes, I think that's a great idea.
